/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AmbientesEditor: typeof import('./src/components/AmbientesEditor.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Projeto3D: typeof import('./src/components/Projeto3D.vue')['default']
    ProjetoForm: typeof import('./src/components/ProjetoForm.vue')['default']
    ResumoCompra: typeof import('./src/components/ResumoCompra.vue')['default']
    RevestimentoCard: typeof import('./src/components/RevestimentoCard.vue')['default']
    RevestimentosEditor: typeof import('./src/components/RevestimentosEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
