/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AmbientesEditor: typeof import('./src/components/AmbientesEditor.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    ChecklistPrint: typeof import('./src/components/ChecklistPrint.vue')['default']
    ExportarPdfButton: typeof import('./src/components/ExportarPdfButton.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MeusProjetos: typeof import('./src/components/MeusProjetos.vue')['default']
    ProdutosEditor: typeof import('./src/components/ProdutosEditor.vue')['default']
    Projeto3D: typeof import('./src/components/Projeto3D.vue')['default']
    ProjetoForm: typeof import('./src/components/ProjetoForm.vue')['default']
    ResumoCompra: typeof import('./src/components/ResumoCompra.vue')['default']
    ResumoPorProduto: typeof import('./src/components/ResumoPorProduto.vue')['default']
    RevestimentoCard: typeof import('./src/components/RevestimentoCard.vue')['default']
    RevestimentosEditor: typeof import('./src/components/RevestimentosEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Wizard: typeof import('./src/components/Wizard.vue')['default']
  }
}
